fixed call to xform by truncating its argument
npatrick04/terminfo pull request #5
Opened 2020-12-24 06:35 UTC by Plisp

This erroneous behaviour was observed while using initc as follows
`(ti:tparm ti:initialize-color 0 60 70 80)`
producing output containing fractions:
`"^[]4;0;rgb:99/A/165/14/66/5^[\\"`
Truncating the integer to be printed produces the correct result
`"^[]4;0;rgb:0F/11/14^[\\"`

2020-12-27 22:19 UTC, npatrick04 commented
Which terminal did you test with?

2020-12-28 08:05 UTC, Plisp commented
libvte terminals (tested using sakura), alacritty, xterm-256color and kitty. Most seem to provide the same (probably xterm's) initc.

2020-12-29 05:46 UTC, npatrick04 requested changes
This fixes the issue in the wrong place.  %doxXs formatters allow for non-integer decimal values.  The problem here is that the arithmetic division defined in terminfo assumes C integral division behavior.   

Please resubmit with the division operator replaced with truncate.

2020-12-29 06:01 UTC, Plisp commented
Ah right sorry. I noticed the truncation behaviour but missed the source entirely.

2020-12-29 18:03 UTC, npatrick04 approved these changes

2020-12-29 18:03 UTC, merged